version: '3.9'
services:
  webapi:
    build:
      context: .
      dockerfile: infinitemoto/Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Port=5432;Database=DummyProjectSql;User Id=postgres;Password=1234

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - "5431:5432"
    # environment:
    env_file:
      - ./postgres.env 
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
